#!/bin/sh
### BEGIN INIT INFO
# Provides:       nafsdm-slave
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the nafsdm-slave daemon
# Description:       starts the nafsdm-slave daemon
### END INIT INFO

/usr/bin/env service nafsdm-slave start
